spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wayfinder
    username: kimilg
    password: dlfrn30
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
